import type { Data } from './types'
import { isoDaysFromNow } from './lib'

const agoISO = (days: number) => new Date(Date.now() - days * 86400000).toISOString()

// Fresh seed every call: due dates are computed relative to "today" so the
// demo always shows 1 overdue (red) + due-soon (amber) orders.
export function makeSeed(): Data {
  return {
    templates: [
      { id: 't-agbada', name: "Agbada / Men's Top", fields: ['neck', 'shoulder', 'chest', 'sleeve length', 'top length', 'wrist'] },
      { id: 't-trouser', name: "Men's Trouser", fields: ['waist', 'hip', 'thigh', 'trouser length', 'ankle'] },
      { id: 't-gown', name: "Women's Gown", fields: ['bust', 'waist', 'hip', 'shoulder', 'sleeve', 'gown length', 'back'] },
      { id: 't-blouse', name: 'Blouse', fields: ['bust', 'shoulder', 'sleeve', 'blouse length'] },
      { id: 't-skirt', name: 'Skirt', fields: ['waist', 'hip', 'skirt length'] },
    ],
    customers: [
      {
        id: 'c-adaeze',
        name: 'Adaeze Okafor',
        phone: '+2348031234567',
        area: 'Surulere, Lagos',
        gender: 'female',
        sets: [
          { templateId: 't-gown', values: { bust: 38, waist: 31, hip: 42, shoulder: 15, sleeve: 22, 'gown length': 58, back: 14.5 } },
        ],
        createdAt: agoISO(40),
      },
      {
        id: 'c-emeka',
        name: 'Emeka Obi',
        phone: '+2348052345678',
        area: 'Ikeja, Lagos',
        gender: 'male',
        sets: [
          { templateId: 't-agbada', values: { neck: 16, shoulder: 18, chest: 42, 'sleeve length': 25, 'top length': 32, wrist: 11 } },
          { templateId: 't-trouser', values: { waist: 34, hip: 41, thigh: 24, 'trouser length': 41, ankle: 15 } },
        ],
        createdAt: agoISO(35),
      },
      {
        id: 'c-funke',
        name: 'Funke Adeyemi',
        phone: '+2348063456789',
        area: 'Yaba, Lagos',
        gender: 'female',
        sets: [
          { templateId: 't-gown', values: { bust: 40, waist: 34, hip: 44, shoulder: 16, sleeve: 24, 'gown length': 60, back: 15 } },
          { templateId: 't-blouse', values: { bust: 40, shoulder: 16, sleeve: 12, 'blouse length': 24 } },
          { templateId: 't-skirt', values: { waist: 34, hip: 44, 'skirt length': 42 } },
        ],
        createdAt: agoISO(28),
      },
      {
        id: 'c-tunde',
        name: 'Tunde Bakare',
        phone: '+2348094567890',
        area: 'Lekki, Lagos',
        gender: 'male',
        sets: [
          { templateId: 't-agbada', values: { neck: 17, shoulder: 19, chest: 46, 'sleeve length': 26, 'top length': 34, wrist: 12 } },
          { templateId: 't-trouser', values: { waist: 38, hip: 44, thigh: 26, 'trouser length': 42, ankle: 16 } },
        ],
        createdAt: agoISO(21),
      },
      {
        id: 'c-chiamaka',
        name: 'Chiamaka Eze',
        phone: '+2347015678901',
        area: 'Ajah, Lagos',
        gender: 'female',
        sets: [
          { templateId: 't-blouse', values: { bust: 34, shoulder: 14, sleeve: 10, 'blouse length': 22 } },
          { templateId: 't-skirt', values: { waist: 28, hip: 38, 'skirt length': 38 } },
        ],
        createdAt: agoISO(14),
      },
      {
        id: 'c-ibrahim',
        name: 'Ibrahim Musa',
        phone: '+2348186789012',
        area: 'Ikorodu, Lagos',
        gender: 'male',
        sets: [
          { templateId: 't-agbada', values: { neck: 15.5, shoulder: 17, chest: 40, 'sleeve length': 24, 'top length': 31, wrist: 10.5 } },
        ],
        createdAt: agoISO(10),
      },
    ],
    orders: [
      {
        id: 'o-1',
        customerId: 'c-emeka',
        garment: 'Agbada (navy)',
        templateId: 't-agbada',
        measurements: { neck: 16, shoulder: 18, chest: 42, 'sleeve length': 25, 'top length': 32, wrist: 11 },
        styleId: 'agbada',
        fabricId: 'adire-indigo',
        price: 45000,
        deposit: 30000,
        dueDate: isoDaysFromNow(-2),
        status: 'sewing',
        notes: 'Matching cap included. Gold embroidery around the neckline.',
        createdAt: agoISO(9),
      },
      {
        id: 'o-2',
        customerId: 'c-adaeze',
        garment: 'Ankara gown',
        templateId: 't-gown',
        measurements: { bust: 38, waist: 31, hip: 42, shoulder: 15, sleeve: 22, 'gown length': 58, back: 14.5 },
        styleId: 'gown',
        fabricId: 'ankara-sunset',
        price: 28000,
        deposit: 10000,
        dueDate: isoDaysFromNow(2),
        status: 'sewing',
        notes: 'Needs it before Sunday service.',
        createdAt: agoISO(6),
      },
      {
        id: 'o-3',
        customerId: 'c-tunde',
        garment: 'Senator wear',
        templateId: 't-agbada',
        measurements: { neck: 17, shoulder: 19, chest: 46, 'sleeve length': 26, 'top length': 34, wrist: 12 },
        styleId: 'senator',
        fabricId: 'senator-navy',
        price: 30000,
        deposit: 0,
        dueDate: isoDaysFromNow(3),
        status: 'new',
        notes: 'Plain navy, minimal pocket detail.',
        createdAt: agoISO(2),
      },
      {
        id: 'o-4',
        customerId: 'c-funke',
        garment: 'Owambe gown',
        templateId: 't-gown',
        measurements: { bust: 40, waist: 34, hip: 44, shoulder: 16, sleeve: 24, 'gown length': 60, back: 15 },
        styleId: 'mermaid',
        fabricId: 'wax-purple',
        price: 55000,
        deposit: 20000,
        dueDate: isoDaysFromNow(9),
        status: 'sewing',
        notes: "Mermaid cut. Aso-ebi for her cousin's wedding.",
        createdAt: agoISO(5),
      },
      {
        id: 'o-5',
        customerId: 'c-ibrahim',
        garment: 'Kaftan (white)',
        templateId: 't-agbada',
        measurements: { neck: 15.5, shoulder: 17, chest: 40, 'sleeve length': 24, 'top length': 31, wrist: 10.5 },
        styleId: 'kaftan',
        fabricId: 'lace-white',
        price: 25000,
        deposit: 10000,
        dueDate: isoDaysFromNow(13),
        status: 'new',
        notes: '',
        createdAt: agoISO(1),
      },
      {
        id: 'o-6',
        customerId: 'c-chiamaka',
        garment: 'Blouse & skirt set',
        templateId: 't-blouse',
        measurements: { bust: 34, shoulder: 14, sleeve: 10, 'blouse length': 22, waist: 28, hip: 38, 'skirt length': 38 },
        styleId: 'blouse',
        fabricId: 'ankara-teal',
        price: 18000,
        deposit: 5000,
        dueDate: isoDaysFromNow(6),
        status: 'ready',
        notes: 'Peplum waist on the blouse.',
        createdAt: agoISO(8),
      },
      {
        id: 'o-7',
        customerId: 'c-emeka',
        garment: 'Suit trouser (2-pc)',
        templateId: 't-trouser',
        measurements: { waist: 34, hip: 41, thigh: 24, 'trouser length': 41, ankle: 15 },
        styleId: 'trouser',
        fabricId: 'plain-charcoal',
        price: 15000,
        deposit: 15000,
        dueDate: isoDaysFromNow(-6),
        status: 'delivered',
        notes: '',
        createdAt: agoISO(15),
      },
      {
        id: 'o-8',
        customerId: 'c-adaeze',
        garment: 'Aso-ebi gown',
        templateId: 't-gown',
        measurements: { bust: 38, waist: 31, hip: 42, shoulder: 15, sleeve: 22, 'gown length': 58, back: 14.5 },
        styleId: 'gown',
        fabricId: 'kente-gold',
        price: 85000,
        deposit: 85000,
        dueDate: isoDaysFromNow(-13),
        status: 'delivered',
        notes: 'Delivered for the Okafor family event.',
        createdAt: agoISO(20),
      },
    ],
    invoices: [
      {
        id: 'i-1',
        number: 'BT-0001',
        customerId: 'c-adaeze',
        lines: [{ label: 'Aso-ebi gown', amount: 85000, orderId: 'o-8' }],
        discount: null,
        depositPaid: 85000,
        status: 'paid',
        createdAt: agoISO(12),
      },
      {
        id: 'i-2',
        number: 'BT-0002',
        customerId: 'c-emeka',
        lines: [
          { label: 'Agbada (navy)', amount: 45000, orderId: 'o-1' },
          { label: 'Suit trouser (2-pc)', amount: 15000, orderId: 'o-7' },
        ],
        discount: { kind: 'flat', value: 5000 },
        depositPaid: 30000,
        status: 'part-paid',
        createdAt: agoISO(1),
      },
    ],
    settings: {
      businessName: 'Golden Thread Stitches',
      tagline: 'bespoke tailoring, Lagos',
      phone: '+2348012345678',
      bankName: 'GTBank',
      accountNumber: '0123456789',
      accountName: 'Golden Thread Stitches',
      currency: '₦',
    },
    bannerDismissed: false,
  }
}
