import type { Availability, Data } from './types'
import { isoDaysFromNow, todayISO } from './lib'
import { bookableDays } from './consult'

const agoISO = (days: number) => new Date(Date.now() - days * 86400000).toISOString()

const AVAILABILITY: Availability = { days: [1, 2, 3, 4, 5, 6], from: '09:00', to: '18:00', slotMins: 30 }

// Seeded consultations are drawn from the *real* slot generator rather than
// offset from now, so they always land inside the tailor's stated hours on a
// working day — a demo opened at 11pm would otherwise show a 2am fitting call.
const bookable = (dayIndex: number, slotIndex: number) => {
  const days = bookableDays(AVAILABILITY, [])
  const day = days[Math.min(dayIndex, days.length - 1)]
  if (!day) return { date: todayISO(), time: '10:00' }
  const slot = day.slots[Math.min(slotIndex, day.slots.length - 1)]
  return { date: day.date, time: slot.time }
}

// Fresh seed every call: due dates are computed relative to "today" so the
// demo always shows 1 overdue (red) + due-soon (amber) orders.
export function makeSeed(): Data {
  return {
    templates: [
      { id: 't-agbada', name: "Agbada / Men's Top", fields: ['neck', 'shoulder', 'chest', 'sleeve length', 'top length', 'wrist'] },
      { id: 't-trouser', name: "Men's Trouser", fields: ['waist', 'hip', 'thigh', 'trouser length', 'ankle'] },
      { id: 't-gown', name: "Women's Gown", fields: ['bust', 'waist', 'hip', 'shoulder', 'sleeve', 'gown length', 'back'] },
      { id: 't-blouse', name: 'Blouse', fields: ['bust', 'shoulder', 'sleeve', 'blouse length'] },
      { id: 't-skirt', name: 'Skirt', fields: ['waist', 'hip', 'skirt length'] },
    ],
    customers: [
      {
        id: 'c-adaeze',
        name: 'Bimbo Ademoye',
        phone: '+2348031234567',
        area: 'Surulere, Lagos',
        email: 'bimbo.ademoye@gmail.com',
        address: '17 Adeniran Ogunsanya St, Surulere',
        gender: 'female',
        sets: [
          { templateId: 't-gown', values: { bust: 38, waist: 31, hip: 42, shoulder: 15, sleeve: 22, 'gown length': 58, back: 14.5 } },
        ],
        createdAt: agoISO(40),
      },
      {
        id: 'c-emeka',
        name: 'Layi Wasabi',
        phone: '+2348052345678',
        area: 'Ikeja, Lagos',
        email: 'layi.w@outlook.com',
        address: '4 Opebi Rd, Ikeja',
        gender: 'male',
        sets: [
          { templateId: 't-agbada', values: { neck: 16, shoulder: 18, chest: 42, 'sleeve length': 25, 'top length': 32, wrist: 11 } },
          { templateId: 't-trouser', values: { waist: 34, hip: 41, thigh: 24, 'trouser length': 41, ankle: 15 } },
        ],
        createdAt: agoISO(35),
      },
      {
        id: 'c-funke',
        name: 'Funke Akindele',
        phone: '+2348063456789',
        area: 'Yaba, Lagos',
        email: 'funke.akindele@yahoo.com',
        address: '22 Herbert Macaulay Way, Yaba',
        gender: 'female',
        sets: [
          { templateId: 't-gown', values: { bust: 40, waist: 34, hip: 44, shoulder: 16, sleeve: 24, 'gown length': 60, back: 15 } },
          { templateId: 't-blouse', values: { bust: 40, shoulder: 16, sleeve: 12, 'blouse length': 24 } },
          { templateId: 't-skirt', values: { waist: 34, hip: 44, 'skirt length': 42 } },
        ],
        createdAt: agoISO(28),
      },
      {
        id: 'c-tunde',
        name: 'Uzor Arukwe',
        phone: '+2348094567890',
        area: 'Lekki, Lagos',
        gender: 'male',
        sets: [
          { templateId: 't-agbada', values: { neck: 17, shoulder: 19, chest: 46, 'sleeve length': 26, 'top length': 34, wrist: 12 } },
          { templateId: 't-trouser', values: { waist: 38, hip: 44, thigh: 26, 'trouser length': 42, ankle: 16 } },
        ],
        createdAt: agoISO(21),
      },
      {
        id: 'c-chiamaka',
        name: 'Mercy Chinwo',
        phone: '+2347015678901',
        area: 'Ajah, Lagos',
        gender: 'female',
        sets: [
          { templateId: 't-blouse', values: { bust: 34, shoulder: 14, sleeve: 10, 'blouse length': 22 } },
          { templateId: 't-skirt', values: { waist: 28, hip: 38, 'skirt length': 38 } },
        ],
        createdAt: agoISO(14),
      },
      {
        id: 'c-ibrahim',
        name: 'Kunle Remi',
        phone: '+2348186789012',
        area: 'Ikorodu, Lagos',
        gender: 'male',
        sets: [
          { templateId: 't-agbada', values: { neck: 15.5, shoulder: 17, chest: 40, 'sleeve length': 24, 'top length': 31, wrist: 10.5 } },
        ],
        createdAt: agoISO(10),
      },
      // Booked through the open link and not measured yet — the empty `sets` is
      // the point: it's what the consultation call is for.
      {
        id: 'c-chidi',
        name: 'Chidi Nwosu',
        phone: '+2349023456781',
        area: '',
        gender: 'male',
        sets: [],
        createdAt: agoISO(0),
      },
    ],
    orders: [
      {
        id: 'o-1',
        customerId: 'c-emeka',
        garment: 'Agbada (navy)',
        templateId: 't-agbada',
        measurements: { neck: 16, shoulder: 18, chest: 42, 'sleeve length': 25, 'top length': 32, wrist: 11 },
        styleId: 'agbada',
        fabricId: 'adire-indigo',
        price: 45000,
        deposit: 30000,
        dueDate: isoDaysFromNow(-2),
        status: 'sewing',
        notes: 'Matching cap included. Gold embroidery around the neckline.',
        createdAt: agoISO(9),
      },
      {
        id: 'o-2',
        customerId: 'c-adaeze',
        garment: 'Ankara gown',
        templateId: 't-gown',
        measurements: { bust: 38, waist: 31, hip: 42, shoulder: 15, sleeve: 22, 'gown length': 58, back: 14.5 },
        styleId: 'gown',
        fabricId: 'ankara-sunset',
        price: 28000,
        deposit: 10000,
        dueDate: isoDaysFromNow(2),
        status: 'sewing',
        notes: 'Needs it before Sunday service.',
        createdAt: agoISO(6),
      },
      {
        id: 'o-3',
        customerId: 'c-tunde',
        garment: 'Senator wear (wine)',
        templateId: 't-agbada',
        measurements: { neck: 17, shoulder: 19, chest: 46, 'sleeve length': 26, 'top length': 34, wrist: 12 },
        styleId: 'senator',
        fabricId: 'aso-oke-red',
        price: 30000,
        deposit: 0,
        dueDate: isoDaysFromNow(3),
        status: 'new',
        notes: 'Wine aso-oke. Minimal pocket detail.',
        createdAt: agoISO(2),
      },
      {
        id: 'o-4',
        customerId: 'c-funke',
        garment: 'Owambe gown',
        templateId: 't-gown',
        measurements: { bust: 40, waist: 34, hip: 44, shoulder: 16, sleeve: 24, 'gown length': 60, back: 15 },
        styleId: 'gown',
        fabricId: 'wax-purple',
        price: 55000,
        deposit: 20000,
        dueDate: isoDaysFromNow(9),
        status: 'sewing',
        notes: "Mermaid cut. Aso-ebi for her cousin's wedding.",
        createdAt: agoISO(5),
      },
      {
        id: 'o-5',
        customerId: 'c-ibrahim',
        garment: 'Kaftan (gold)',
        templateId: 't-agbada',
        measurements: { neck: 15.5, shoulder: 17, chest: 40, 'sleeve length': 24, 'top length': 31, wrist: 10.5 },
        styleId: 'kaftan',
        fabricId: 'kente-gold',
        price: 25000,
        deposit: 10000,
        dueDate: isoDaysFromNow(13),
        status: 'new',
        notes: '',
        createdAt: agoISO(1),
      },
      {
        id: 'o-6',
        customerId: 'c-chiamaka',
        garment: 'Ankara dashiki',
        templateId: 't-blouse',
        measurements: { bust: 34, shoulder: 14, sleeve: 10, 'blouse length': 22, waist: 28, hip: 38, 'skirt length': 38 },
        styleId: 'dashiki',
        fabricId: 'ankara-teal',
        price: 18000,
        deposit: 5000,
        dueDate: isoDaysFromNow(6),
        status: 'ready',
        notes: 'Loose fit, embroidered neckline. Matching skirt to follow.',
        createdAt: agoISO(8),
      },
      {
        id: 'o-7',
        customerId: 'c-emeka',
        garment: 'Suit trouser (2-pc)',
        templateId: 't-trouser',
        measurements: { waist: 34, hip: 41, thigh: 24, 'trouser length': 41, ankle: 15 },
        styleId: 'trouser',
        fabricId: 'adire-indigo',
        price: 15000,
        deposit: 15000,
        dueDate: isoDaysFromNow(-6),
        status: 'delivered',
        notes: '',
        createdAt: agoISO(15),
      },
      {
        id: 'o-8',
        customerId: 'c-adaeze',
        garment: 'Aso-ebi gown',
        templateId: 't-gown',
        measurements: { bust: 38, waist: 31, hip: 42, shoulder: 15, sleeve: 22, 'gown length': 58, back: 14.5 },
        styleId: 'gown',
        fabricId: 'kente-gold',
        price: 85000,
        deposit: 85000,
        dueDate: isoDaysFromNow(-13),
        status: 'delivered',
        notes: 'Delivered for the Okafor family event.',
        createdAt: agoISO(20),
      },
    ],
    invoices: [
      {
        id: 'i-1',
        number: 'BT-0001',
        customerId: 'c-adaeze',
        lines: [{ label: 'Aso-ebi gown', amount: 85000, orderId: 'o-8' }],
        discount: null,
        depositPaid: 85000,
        status: 'paid',
        createdAt: agoISO(12),
      },
      {
        id: 'i-2',
        number: 'BT-0002',
        customerId: 'c-emeka',
        lines: [
          { label: 'Agbada (navy)', amount: 45000, orderId: 'o-1' },
          { label: 'Suit trouser (2-pc)', amount: 15000, orderId: 'o-7' },
        ],
        discount: { kind: 'flat', value: 5000 },
        depositPaid: 30000,
        status: 'part-paid',
        createdAt: agoISO(1),
      },
    ],
    consultations: [
      {
        id: 'k-1',
        customerId: 'c-chidi',
        name: 'Chidi Nwosu',
        phone: '+2349023456781',
        ...bookable(0, 0),
        durationMins: 30,
        channel: 'whatsapp',
        link: '',
        styleId: 'senator',
        templateId: 't-agbada',
        photo: '',
        photoPending: true,
        note: "It's for my brother's wedding in September.",
        status: 'upcoming',
        createdAt: agoISO(0),
      },
      {
        id: 'k-2',
        customerId: 'c-adaeze',
        name: 'Bimbo Ademoye',
        phone: '+2348031234567',
        ...bookable(1, 6),
        durationMins: 30,
        channel: 'whatsapp',
        link: '',
        styleId: 'gown',
        templateId: 't-gown',
        photo: '',
        photoPending: false,
        note: 'Want to re-check my measurements, I have lost some weight.',
        status: 'upcoming',
        createdAt: agoISO(1),
      },
    ],
    // A one-person shop. No lock screen, no PINs, nothing different from before
    // — until the owner adds somebody in settings, which is what switches the
    // whole multi-staff experience on.
    staff: [
      {
        id: 'st-owner',
        name: 'Tolu Adeyinka',
        role: 'owner',
        pin: '',
        canSeeContacts: true,
        lastActiveAt: new Date().toISOString(),
        createdAt: agoISO(90),
      },
    ],
    currentStaffId: 'st-owner',
    settings: {
      businessName: 'Golden Thread Stitches',
      tagline: 'bespoke tailoring, Lagos',
      phone: '+2348012345678',
      bankName: 'GTBank',
      accountNumber: '0123456789',
      accountName: 'Golden Thread Stitches',
      currency: '₦',
      // Prefilled so a tailor can send a working booking link having configured
      // nothing at all — Mon–Sat, 9 to 6, half-hour calls.
      callChannel: 'whatsapp',
      callLink: '',
      availability: AVAILABILITY,
    },
    bannerDismissed: false,
  }
}
